### PR TITLE
Warning fixes. Don't even build static functions that aren't called

### PR DESCRIPTION
**Pull request by robertlipe**
+ Other minor warning fixes in boot2.

### CODE REVIEW

**Comment by Avamander** [comment]
As this is a SDK, having unused functions is fine, they're designed to be used by projects built on top.

**Comment by robertlipe** [comment]
The boot functions exist elsewhere in the tree.  The code in debug is called elsewhere in the same file, but the call is bracketed by conditional compilation, so I moved the definition into the same #ifdef as the call. Now they're only built if they're actually used.

Warnings look  unprofessional and make it hard to find actual problems.

**Comment by Avamander** [comment]
Could you please link to where else they exist?

Secondly, one PR should really implement one feature at once, otherwise it complicates keeping track of what's being discussed and changed.

**Comment by robertlipe** [comment]
Scrapping this PR so I can spend the day doing branch management instead of fixes...

**Pull request closed without merging**
