### PR TITLE
Improved README.md

### PR DESCRIPTION
**Pull request by panos**
- Removed redundant instructions (Exporting variables doesn't seem to be necessary in order for compiling to work)
- Improved wording

### CODE REVIEW

**Comment by Avamander** [comment]
The variables have to be set if it can't guess them automatically, I wouldn't remove that section.

**Comment by panos** [comment]
> The variables have to be set if it can't guess them automatically, I wouldn't remove that section.

I mean, is there any other option that could be chosen over instead?

**Comment by Avamander** [comment]
> I mean, is there any other option that could be chosen over instead?

Elaborate.

**Comment by panos** [comment]
> > I mean, is there any other option that could be chosen over instead?
> 
> Elaborate.

There are options such as `BL60X` and `BL606` for `hal_drv`, but they are not projected to be used due to the way that the `Makefile`'s are written under `customer_app`. There's no way that any other option other than `BL602`, without the user explicitly desiring to do so.

For the same reason, I wouldn't understand why guessing the directory could go wrong under a Unix-like environment either.

**Comment by Avamander** [comment]
> For the same reason, I wouldn't understand why guessing the directory could go wrong under a Unix-like environment either.

It assumes the examples are inside the SDK folder, this would break when someone copies an example out and doesn't set the variable. The documentation would be better if it mentioned this nuance.

**Comment by panos** [comment]
> > For the same reason, I wouldn't understand why guessing the directory could go wrong under a Unix-like environment either.
> 
> It assumes the examples are inside the SDK folder, this would break when someone copies an example out and doesn't set the variable. The documentation would be better if it mentioned this nuance.

Will correct in a bit.

**Comment by panos** [comment]
Fixed the conflict.

**Pull request merged**
