### PR TITLE
README: add some more hardware details (evaluation boards and core type)

### PR DESCRIPTION
**Pull request by v01d**
Added some information about current evaluation boards available and hint about RISC-V core used.

### CODE REVIEW

**Review by gamelaster — CHANGES_REQUESTED** [review]
From what I know, it's SiFive E24, so question mark can be removed.

**Comment by v01d** [comment]
Yeah, AFAIK as well. But I suppose until it is official we should not treat it as certain?

**Comment by gamelaster** [comment]
Well, I got confirmed from some sources that it's SiFive E24, so it should be fine.

**Comment by v01d** [comment]
Ok! I changed the text accordingly.

**Comment by gamelaster** [comment]
Thank you very much for your pull request!
For receiving the free PineCone, please sign up at [this link](https://nutcracker.pine64.org/free-evb/).
(If there will be any issues with signing up, please let me know here).

**Pull request merged**
