### PR TITLE
Build docs from source .rst files

### PR DESCRIPTION
**Pull request by Newbytee**
This PR makes the docs build from their source .rst files. This means we won't manually have to translate the UI elements, and should also allow for easier translation of them.

Note that there are a bunch of warnings when building this, but they should only affect documentation that isn't included in the official Chinese build anyway (yes, there are a bunch of files with text that aren't built into HTML for some reason), so I'm not sure whether those files should be included at all.

### CODE REVIEW

**Comment by username223** [comment]
Did you build these docs using [sphinx](https://www.sphinx-doc.org/en/master/usage/quickstart.html) or just copy them?

I considered doing some basic Google translate of the docs to English, but I'm not sure if it makes sense to do it directly in the current HTML or in the `sphinx` documents.

It seems like the `docs/html/_sources/index.rst.txt` file is a product of compilation by `sphinx` when building the documentation. The semi-raw sources can be found in the directories it points to, but it's not easily buildable because it needs at least a `conf.py` that specifies e.g. author and copyright.

This repo really needs an issue tracker.

**Comment by Newbytee** [comment]
> Did you build these docs using [sphinx](https://www.sphinx-doc.org/en/master/usage/quickstart.html) or just copy them?

I just copied them as it seems the repository is, as you later noted, lacking certain components necessary for building. This is definitely not an ideal solution.

> I considered doing some basic Google translate of the docs to English, but I'm not sure if it makes sense to do it directly in the current HTML or in the `sphinx` documents.

Yeah, probably makes more sense to translate the sphinx docs.

> It seems like the `docs/html/_sources/index.rst.txt` file is a product of compilation by `sphinx` when building the documentation. The semi-raw sources can be found in the directories it points to, but it's not easily buildable because it needs at least a `conf.py` that specifies e.g. author and copyright.

I had not, however, noticed this part.

**Comment by Newbytee** [comment]
I'll look into getting it building from the sphinx files.

**Comment by username223** [comment]
Is this PR stable? If so, I'll get a chip-awarding PR in based on this translating some raw files and `.txt` files.

**Comment by Newbytee** [comment]
> Is this PR stable? If so, I'll get a chip-awarding PR in based on this translating some raw files and `.txt` files.

I'm thinking I'll force-push over all of this once I have it building like it should. Right now it builds, but the output does contain anything. It's not finding the .rst files for some reason (even after renaming them from .rst.txt to .rst).

**Comment by username223** [comment]
> > Is this PR stable? If so, I'll get a chip-awarding PR in based on this translating some raw files and `.txt` files.
> 
> I'm thinking I'll force-push over all of this once I have it building like it should. Right now it builds, but the output does contain anything. It's not finding the .rst files for some reason (even after renaming them from .rst.txt to .rst).

Alright, let me know when it builds, then I'll do a PR after that.

**Comment by Newbytee** [comment]
@username223 It builds now. I will need to hunt down the theme used (shouldn't be too hard) and fix some errors, but what's here now shouldn't change too much.

**Comment by username223** [comment]
@Newbytee Cool, I'll get a PR up.

**Comment by username223** [comment]
@Newbytee Trying to compile right now doesn't add the updated text. Adding the line `master_doc = 'index'` to `conf.py` in order to point `sphinx` at the index.rst file makes it work correctly.

**Comment by username223** [comment]
@Newbytee I'm getting quite a lot of errors because there are no images.

The images can be found in ``zh/html/_images`, but they're all in the same folder and it seems like `sphinx` expects them to be local to the `.rst`s.

It also does not seem like the images always retain their original names, for instance there's a
```
/home/daniel/gitas/bl_iot_sdk/docs/en/source/Components/BLE/ble_stack/ble_stack.rst:: WARNING: image file not readable: Components/BLE/ble_stack/imgs/image1.png
```
But also a
```
/home/daniel/gitas/bl_iot_sdk/docs/en/source/Components/Network/wifi/wifi.rst:: WARNING: image file not readable: Components/Network/wifi/imgs/image1.png
```
The actual image shown in the Chinese docs is `image123.png`.

**Comment by Newbytee** [comment]
> @Newbytee I'm getting quite a lot of errors because there are no images.

Yeah, I'm on this right now. If you fetch the latest changes you'll see I'm down to 138 warnings (used to be over 300).

**Comment by username223** [comment]
@Newbytee Alright, cool, if you're working on the images then I'll just continue on the translation.

**Comment by Newbytee** [comment]
I also noticed that interestingly some parts of the docs are not part of the table of contents, such as the Quickstart Guide. I'm thinking it would be reasonable to add that to the table of contents.

Do you have any thoughts, @username223?

**Comment by username223** [comment]
@Newbytee That definitely makes sense.

**Comment by Newbytee** [comment]
Something I noticed: Seems one image is missing even in the Chinese docs in the Romfs section (9.2).

**Comment by username223** [comment]
@Newbytee I see.
It's likely not included due to us only having the images that were found during the Chinese building. :/

Might be necessary to create a new one from scratch, although that's probably a little ways out.

**Comment by Newbytee** [comment]
Also something strange: There is a bunch of documentation that is not built in the Chinese documentation, but still contains text. I'm not sure whether this should be built, as I imagine there is a reason it was not included in the first place.

**Comment by Newbytee** [comment]
@muscache Do you speak Chinese? Does the stuff in the following files make sense to include?

Quickstart_Guide/get_started
Quickstart_Guide/Linux/Quickstart_Linux_ubuntu
Quickstart_Guide/Windows/Quickstart_Windows_msys
Examples/demo_at/AT
Examples/demo_audio_udp/audio_udp
Examples/demo_hbnram/hbnram
Examples/demo_zb/zigbee
Examples/benchmark_security_aes/benchmark_security_aes_gcm
Examples/demo_cronalarm/cronalarm
Examples/demo_dac/DAC
Examples/sdk_app_pwm/pwm

It is currently built in my pull request. See here: https://github.com/Newbytee/bl_iot_sdk/tree/initial-eng-docs/docs/en/build/html

**Comment by Newbytee** [comment]
> @Newbytee Trying to compile right now doesn't add the updated text. Adding the line `master_doc = 'index'` to `conf.py` in order to point `sphinx` at the index.rst file makes it work correctly.

Strangely enough this doesn't seem to work for me. I need to delete the build directory for changes to take place.

**Comment by gamelaster** [comment]
Hello @Newbytee and @username223 ,

Thank you for your work. Please, can you remove all doctrees from the pull requests and add doctrees into gitignore?

Thanks

**Comment by Newbytee** [comment]
> Thank you for your work. Please, can you remove all doctrees from the pull requests and add doctrees into gitignore?

Done

**Comment by Avamander** [comment]
I have a feeling the built doc should reside in a separate repository, that would make the commit log look nicer and allow easier publishing.

**Comment by Newbytee** [comment]
> I have a feeling the built doc should reside in a separate repository, that would make the commit log look nicer and allow easier publishing.

Thinking I should gitignore the build directory too?

**Comment by muscache** [comment]
@Newbytee what is your opinion on having just the chinese docs and writing a script that programatically generates docs of any language using the source files?

**Comment by Newbytee** [comment]
> @Newbytee what is your opinion on having just the chinese docs and writing a script that programatically generates docs of any language using the source files?

It seems Sphinx has some sort of internationalisation architecture, maybe we can leverage it?

https://www.sphinx-doc.org/en/master/extdev/i18n.html

This answer seems to imply we'll still need to do some scripting ourselves though: https://stackoverflow.com/a/63053715

I'm not super familiar with how Sphinx works, but keeping the Chinese docs and hooking up something that manages translation sounds reasonable to me.

**Comment by gamelaster** [comment]
Hello @Newbytee , @muscache and @username223 ,

We finally decided to separate docs to [another repository](https://github.com/pine64/ble602-docs). @Newbytee if you can, please, move the docs into the new repo and make pull request. After merging, all of you guys will receive free EVB.

Thanks

**Comment by Avamander** [comment]
> It seems Sphinx has some sort of internationalisation architecture, maybe we can leverage it?

This would be a very reasonable next PR. Especially considering all the translation wishes.

**Comment by Newbytee** [comment]
> We finally decided to separate docs to [another repository](https://github.com/pine64/ble602-docs). @Newbytee if you can, please, move the docs into the new repo and make pull request. After merging, all of you guys will receive free EVB.

Done: https://github.com/pine64/ble602-docs/pull/1

**Comment by gamelaster** [comment]
Closed in favor of pine64/ble602-docs#1 .

**Pull request closed without merging**
