### PR TITLE
Add ROM info to Hardware Notes

### PR DESCRIPTION
**Pull request by tchebb**
Did some more investigation of the ROM. Adding my findings to the notes.

### CODE REVIEW

**Comment by Avamander** [comment]
Can you please make this PR towards https://github.com/pine64/ble602-docs instead?

**Comment by tchebb** [comment]
Do you want me to move the whole `hardware_notes.md` file there? I added it yesterday with #35. If so, do you also think we should move the bulk of the README ("Hardware" and "Comparison with ESP8266") to the docs repo?

**Comment by Avamander** [comment]
The README.md should stay because it can give an overview of the repository, but the rest of the docs should reside in the separate repository.

**Comment by tchebb** [comment]
Closing in favor of pine64/bl602-docs#5

**Pull request closed without merging**
