### PR TITLE
Force -Wall & -Werror, fix build warnings

### PR DESCRIPTION
**Pull request by konradybcio**

### CODE REVIEW

**Comment by robertlipe** [comment]
+1 to -Werror.
The rest of this overlaps heavily with https://github.com/pine64/bl_iot_sdk/pull/33 which has been in code jail for over a month. I approve of merging them, but we need to work together and quit duplicating effort.

**Comment by konradybcio** [comment]
So.. should we perhaps get #33 merged and *then* only merge my Werror/Wall enablement commit so that it builds properly?

**Comment by robertlipe** [comment]
Yes. Id hope that after committing the first that very little of the second
remains. (I think I saw you fix an additional data type to avoid a cast in
DAC or something...)

It's been held "for testing" without definition of what that testing is.
They're static functions that have no callers. They were seemingly left
after a copy/paste with the callers removed. Since they're static, they're
known to not have callers. I don't know why these are stuck.

My hardware arrived just yesterday, but there's no working flash tool for
MacOS yet. It's not clear what the required acceptance test is as I don't
think we have a test suite...

**Comment by konradybcio** [comment]
(bump)

**Comment by konradybcio** [comment]
(bump?)

**Comment by gamelaster** [comment]
Thank you very much for your pull request!
For receiving the free PineCone, please sign up at [this link](https://nutcracker.pine64.org/free-evb/).
(If there will be any issues with signing up, please let me know here).

**Pull request merged**
