### PR TITLE
Begin english index translation

### PR DESCRIPTION
**Pull request by Martoni**
I just began the english translation of the html documentation.
It seems to be automatic html generation, then it's maybe not the right way to do it ?

### CODE REVIEW

**Comment by maidenone** [comment]
see https://github.com/pine64/bl_iot_sdk/pull/12

**Comment by muscache** [comment]
@Martoni This repo uses Sphinx to generate HTML docs (the config wasn't commited here though). Don't edit the HTML directly but rather edit the source .rst files (See #5)

**Comment by Avamander** [comment]
We'll probably use the Sphinx i18n support on the new https://github.com/pine64/ble602-docs repository.

**Comment by Avamander** [comment]
You can now nicely update the `en` source files in https://github.com/pine64/bl602-docs, please do any translation efforts there.

**Pull request closed without merging**
