### PR TITLE
ci: gitignore backup files

### PR DESCRIPTION
**Pull request by serv-inc**
created by emacs and e.g. mv -b

### CODE REVIEW

**Comment by gamelaster** [comment]
Well, this looks like only Emacs related, so I'm not sure if it should be here. Will think about this

**Comment by WildCryptoFox** [comment]
(Regardless of this PR) You might want a global gitignore? `git config --global core.excludesFile ~/config/git-ignore`

I think it makes sense to include this, in addition to vim's `.*.swp`. At least for vim, you can tell it to store these files elsewhere. `:set dir=$XDG_RUNTIME_DIR/vim/`

**Comment by Avamander** [comment]
Does EMACS leave these files behind often?

**Comment by serv-inc** [comment]
It does leave them behind if a file is not in git /version control. If it is version-controlled, that is used instead.

**Comment by gamelaster** [comment]
Closing since this is only Emacs related.

**Pull request closed without merging**
