### PR TITLE
build: update requirements.txt

### PR DESCRIPTION
**Pull request by serv-inc**
to get flash_build.py to run

### CODE REVIEW

**Comment by serv-inc** [comment]
this actually runs fine with python 3 with the requirements already in the script . Feel free to close this without merging.

**Comment by gamelaster** [comment]
Is this patch required for Python 2.x? If yes, then I will merge it.

**Comment by Avamander** [comment]
Python2 is EOL, I don't think it should be supported.

**Comment by serv-inc** [comment]
It is required for Python 2. Still, an alternative would be to use https://github.com/pine64/bl_iot_sdk/pull/54 . That simply documents that python3 should be used, making it shell-executable.

**Pull request closed without merging**
